# Generated by Django 5.2.14 on 2026-05-09 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupor', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='moderation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='blog',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('blocked', 'Заблокировано')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('blocked', 'Заблокировано')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderation_reason', models.TextField(blank=True, null=True, verbose_name='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rupor.blog')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rupor.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
