# Generated by Django 5.2.14 on 2026-05-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupor', '0003_blog_moderation_reason_blog_moderation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Эмбеддинг текста'),
        ),
    ]
